# Generated by Django 3.2.5 on 2021-07-29 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teng', '0002_remove_supplier_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=90),
            preserve_default=False,
        ),
    ]
