# Generated by Django 3.2.5 on 2021-07-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teng', '0002_keyword_searched_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_website_turkey',
            name='english_keyword',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='visited_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword_website_turkey',
            name='chinese_keyword',
            field=models.CharField(max_length=90, null=True, unique=True),
        ),
    ]
