# Generated by Django 3.2.5 on 2021-07-29 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teng', '0003_supplier_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='test',
        ),
    ]
